#FROM node:16-stretch
#FROM node:16-buster
FROM ubuntu:20.04
LABEL maintainer="libo<156884481@qq.com>"
LABEL version="1.0"

#RUN sed -i 's#http://deb.debian.org#https://mirrors.tuna.tsinghua.edu.cn#g' /etc/apt/sources.list
#RUN sed -i 's#http://ports.ubuntu.com#https://mirrors.tuna.tsinghua.edu.cn#g' /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -y vim
    #npm config set registry https://registry.npm.taobao.org --global && \
    #npm config set disturl https://npm.taobao.org/dist --global && \
    #npm install -g hexo-cli && \
    #npm install -g hexo
    
#RUN git config --global user.email "156884481@qq.com" && \
#    git config --global user.name "thinker"

WORKDIR /data

ENTRYPOINT bash

#sed -i 's#https://mirrors.tuna.tsinghua.edu.cn#http://deb.debian.org#g' /etc/apt/sources.list

# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
#deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal main restricted universe multiverse
#deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal main restricted universe multiverse
#deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-updates main restricted universe multiverse
#deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-updates main restricted universe multiverse
#deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-backports main restricted universe multiverse
#deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-backports main restricted universe multiverse
#deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-security main restricted universe multiverse
#deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-security main restricted universe multiverse

#sed -i 's#http://ports.ubuntu.com/ubuntu-ports#https://mirrors.tuna.tsinghua.edu.cn/ubuntu/#g' /etc/apt/sources.list


#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



FROM node:16-buster
LABEL maintainer="libo<156884481@qq.com>"
LABEL version="1.0"

RUN sed -i 's#http://ports.ubuntu.com#http://mirrors.tuna.tsinghua.edu.cn#g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y vim git

ADD node-v14.17.5-linux-arm64.tar.xz /opt

RUN mv /opt/node-v14.17.5-linux-arm64 /opt/node && \ 
    ln -s /opt/node/bin/node /usr/local/sbin/ && \
    ln -s /opt/node/bin/npm /usr/local/sbin/ && \
    npm config set registry https://registry.npm.taobao.org --global && \
    npm config set disturl https://npm.taobao.org/dist --global && \
    npm install -g hexo-cli && \
    npm install -g hexo
    
#RUN git config --global user.email "156884481@qq.com" && \1
#    git config --global user.name "thinker"

WORKDIR /data

ENTRYPOINT bash

#sed -i 's#https://mirrors.tuna.tsinghua.edu.cn#http://deb.debian.org#g' /etc/apt/sources.list

# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
#deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal main restricted universe multiverse
#deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal main restricted universe multiverse
#deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-updates main restricted universe multiverse
#deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-updates main restricted universe multiverse
#deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-backports main restricted universe multiverse
#deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-backports main restricted universe multiverse
#deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-security main restricted universe multiverse
#deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ focal-security main restricted universe multiverse

#sed -i 's#http://ports.ubuntu.com#https://mirrors.tuna.tsinghua.edu.cn#g' /etc/apt/sources.list

#Nodesource 镜像使用帮助
#Nodesource 为 debian, ubuntu, fedora, RHEL 等发行版提供预编译的 nodejs 和 npm 等软件包。

#debian/ubuntu 使用方法
#curl -sL https://deb.nodesource.com/setup | sudo bash -
#编辑 /etc/apt/sources.list.d/nodesource.list，把 https://deb.nodesource.com/node/ 替换为 http://mirrors.cloud.tencent.com/nodesource/deb/ 即可。


#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

#apt-get install gnutls-bin
#git config --global http.sslVerify false
#git config --global http.postBuffer 1048576000